bot_token: "123456789:ABCDEF_example_bot_token"
watch_list:
  - sources:
      - "https://t.me/SugarPic/71831"
      - "@AnotherChannel"
    forward_to:
      - "@MyForwardChannel"
      - 123456789
    include_service_messages: false
  - source: -1002222333344
    forward_to:
      - 987654321
polling:
  drop_pending_updates: true
